repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: pretty-format-json
        args: [
          '--autofix',
        ]
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: git://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6
  - repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
      - id: pydocstyle
  - repo: git://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: [
          '--in-place',
          '--wrap-summaries=72',
          '--wrap-descriptions=72',
          '--pre-summary-newline',
          '--make-summary-multi-line'
        ]
  - repo: git://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
  - repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-crlf
      - id: remove-tabs
