name: mdp_video_generation
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - aiohttp=3.5.4
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - async-timeout=3.0.1
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - boost=1.67.0
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2019.1.23
  - caffe=1.0
  - cairo=1.14.12
  - certifi=2019.3.9
  - cffi=1.11.5
  - chainer=4.5.0
  - click=7.0
  - constantly=15.1.0
  - cryptography=2.4.2
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - cytoolz=0.9.0.1
  - dask-core=1.1.0
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - ffmpeg=4.0
  - filelock=3.0.10
  - flask=1.0.2
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - gflags=2.2.2
  - glib=2.56.2
  - glog=0.3.5
  - gmp=6.1.2
  - graphite2=1.3.12
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - idna_ssl=1.1.0
  - imageio=2.5.0
  - incremental=17.5.0
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - itsdangerous=1.1.0
  - jasper=2.0.14
  - jedi=0.13.1
  - jinja2=2.10
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - leveldb=1.20
  - libboost=1.67.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.8
  - llvmlite=0.27.0
  - lmdb=0.9.23
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - multidict=4.5.2
  - mypy=0.701
  - mypy_extensions=0.4.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nccl=1.3.5
  - ncurses=6.1
  - ninja=1.8.2
  - notebook=5.7.2
  - numba=0.42.0
  - numpy-base=1.16.3
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1c
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.1
  - pixman=0.34.0
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.7
  - ptyprocess=0.6.0
  - py-boost=1.67.0
  - py-opencv=3.4.2
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.19
  - pygments=2.2.0
  - pyhamcrest=1.9.0
  - pyopenssl=18.0.0
  - pyqt=5.9.2
  - python=3.6.7
  - python-dateutil=2.7.5
  - python-engineio=3.5.1
  - python-gflags=3.1.2
  - python-leveldb=0.20
  - python-socketio=4.0.0
  - pytorch=0.4.1
  - pytz=2018.7
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtconsole=4.4.2
  - readline=7.0
  - scikit-learn=0.21.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - snappy=1.1.7
  - sqlite=3.25.3
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=18.9.0
  - typed-ast=1.3.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.6.0
  - pip:
    - absl-py==0.3.0
    - astor==0.7.1
    - blessings==1.7
    - cfgv==3.2.0
    - chardet==3.0.4
    - cloudpickle==0.5.5
    - cupy==4.4.1
    - cycler==0.10.0
    - cython==0.28.5
    - dask==0.19.1
    - distlib==0.3.1
    - dlib==19.17.0
    - dm-sonnet==1.23
    - docopt==0.6.2
    - fastrlock==0.4
    - flamegraph==0.1
    - gast==0.2.0
    - gpustat==0.5.0
    - grpcio==1.14.1
    - h5py==2.9.0
    - identify==1.4.26
    - imgpy==1.1.0
    - importlib-metadata==1.7.0
    - importlib-resources==3.0.0
    - imutils==0.5.2
    - kaggle==1.5.1.1
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - kiwisolver==1.0.1
    - line-profiler==2.1.2
    - markdown==3.1
    - mock==2.0.0
    - moviepy==0.2.3.5
    - mp3-tagger==1.0
    - networkx==1.8.1
    - nodeenv==1.4.0
    - numpy==1.16.3
    - nvidia-ml-py3==7.352.0
    - nvvl==1.0
    - opencv-python==3.4.4.19
    - pbr==5.1.3
    - pillow==5.2.0
    - pprofile==1.11.0
    - pre-commit==2.6.0
    - protobuf==3.7.1
    - psutil==5.4.7
    - pyparsing==2.2.0
    - python-graphviz==0.9
    - python-slugify==1.2.6
    - pytorchviz==0.0.1
    - pywavelets==1.0.0
    - pyyaml==3.13
    - requests==2.21.0
    - scikit-image==0.14.0
    - scipy==1.1.0
    - setuptools==41.0.1
    - six==1.12.0
    - sonnet==0.1.6
    - tensorboard==1.13.1
    - tensorboardx==1.4
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - tensorflow-hub==0.2.0
    - termcolor==1.1.0
    - tflearn==0.3.2
    - toml==0.10.1
    - toolz==0.9.0
    - torch==0.4.1
    - torchvision==0.2.1
    - tqdm==4.59.0
    - unidecode==1.0.23
    - urllib3==1.22
    - virtualenv==20.0.30
    - werkzeug==0.14.1
    - wheel==0.33.1
    - zipp==3.1.0
