name: mdp_video_generation
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.67.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.2
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - pandas=1.1.5
  - pcre=8.44
  - pillow=8.1.2
  - pip=21.0.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.13
  - python-dateutil=2.8.1
  - pytorch=0.4.1
  - pytz=2021.1
  - qt=5.9.7
  - readline=8.1
  - seaborn=0.11.1
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.35.1
  - tk=8.6.10
  - torchvision=0.2.1
  - tornado=6.1
  - tqdm=4.59.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - cached-property==1.5.2
    - decorator==4.4.2
    - gast==0.4.0
    - grpcio==1.36.1
    - h5py==3.1.0
    - imageio==2.9.0
    - importlib-metadata==3.7.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - mock==4.0.3
    - networkx==2.5
    - opencv-python==4.5.1.48
    - protobuf==3.15.6
    - python-graphviz==0.16
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - scipy==1.5.4
    - tensorboard==1.13.1
    - tensorboardx==2.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - tensorflow-hub==0.2.0
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - torchviz==0.0.1
    - typing-extensions==3.7.4.3
    - werkzeug==1.0.1
    - zipp==3.4.1
