from .mocogan_models import VideoDiscriminator, PatchVideoDiscriminator, CategoricalVideoDiscriminator
from .mocogan_models import ImageDiscriminator, PatchImageDiscriminator
from .mocogan_models import MergedDiscriminator
from .mocogan_models import VideoGenerator, NormalizedVideoGenerator

from .temporal_convnet import TemporalVideoDiscriminator, TemporalVideoDiscriminatorWeighted, TemporalConvNet
